apiVersion: v1
kind: Service
metadata:
    name: "hasin-56af"
    labels:
        app: "hasin-56af"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "hasin-56af"